<div class="rounded_bl"><div class="rounded_b2"><div class="rounded_tl"><div class="rounded_t2"> 

<table style='margin-left:4px;' class='<?= $css; ?>'>

<thead>
<tr><td colspan='7' class='header'><?= $header; ?><td></tr>
</thead>

<tbody>
<tr><td>W</td><td>T</td><td>F</td><td>S</td><td>S</td><td>M</td><td>T</td></tr>
<?php
for($i=0; $i<$weeksInMonth; $i++) {
	// display the row
	echo '<tr>';
	// display the column
	for ($j=0; $j < 7; $j++) {
		// design each cell
		if ($cell[$i][$j]['link'] != 'none') {
			$class = 'withLink';
		}
		else if ($cell[$i][$j]['isToday']) {
			$class = 'today';
		}
		else {
			$class = 'withoutLink';
		}

		echo "<td class='$class'>";
		
		// display cell value
		echo $cell[$i][$j]['day'];
		
		echo '</td>';
	}
	
	// end row
	echo '</tr>';
}
?>
</tbody>

<tfoot>
<tr><td colspan='7'></td></tr>
</tfoot>
</table>

<table style='width:100%'>
<tr><td style='text-align:left;'><?= $prevMonth; ?></td><td style='text-align:right;'><?= $nextMonth; ?></td></tr>
</table>
</div></div></div></div><div class="rounded_clear">&nbsp;</div>
