<table class='<?= $css; ?>'>
<thead>
<tr><th>&nbsp;<a href="#" onclick="<?= $lastYear; ?>" title='Prev Year'><<</a></th>
<th>&nbsp;<a href="#" onclick="<?= $lastMonth; ?>" title='Prev Month'><</a></th>
<th colspan='3'><?= $header; ?></th>
<th><a href="#" onclick="<?= $nextMonth; ?>" title='Next Month'>></a>&nbsp;</th>
<th>&nbsp;<a href="#" onclick="<?= $nextYear; ?>" title='Next Year'>>></a></th>
</tr>
</thead>

<tbody>
<tr><th>S</th><th>M</th><th>T</th><th>W</th><th>Th</th><th>F</th><th>S</th></tr>
<?php

for($i=0; $i<$weeksInMonth; $i++) {
	// display the row
	echo '<tr>';
	// display the column
	for ($j=0; $j < 7; $j++) {
		// design each cell
		if ($cell[$i][$j]['link'] != 'none') {
			$class = 'withLink';
		}
		else if ($cell[$i][$j]['isToday']) {
			$class = 'today';
		}
		else {
			$class = 'withoutLink';
		}

		echo "<td class='$class'>";
		
		// display cell value
		echo $cell[$i][$j]['day'];
		
		echo '</td>';
	}
	
	// end row
	echo '</tr>';
}
?>
</tbody>

<tfoot>
<tr><th colspan='7'><a href="#" onclick="<?= $todayLink; ?>">
Today is <?= $todayText; ?></a></th></tr>
</tfoot>

</table>
