<table class='<?= $css; ?>'>
<thead>
<tr><th>&nbsp;<a href="#" onclick="<?= $lastYear; ?>"title='Prev Year'><<</a></th>
<th>&nbsp;<a href="#" onclick="<?= $lastMonth; ?>" title='Prev Month'><</a></th>
<th colspan='3'><?= $header; ?></th>
<th><a href="#" onclick="<?= $nextMonth; ?>" class='headerNav' title='Next Month'>></a>&nbsp;</th>
<th>&nbsp;<a href="#" onclick="<?= $nextYear; ?>" class='headerNav' title='Next Year'>>></a></th>
</tr>
</thead>

<tbody>
<tr><th>Sun</th><th>Mon</th><th>Tue</th><th>Wed</th><th>Thur</th><th>Fri</th><th>Sun</th></tr>
<?php
for($i=0; $i<$weeksInMonth; $i++) {
	// display the row
	echo '<tr>';
	// display the column
	for ($j=0; $j < 7; $j++) {
		// design each cell
		if ($cell[$i][$j]['link'] != 'none') {
			$class = 'withLink';
		}
		else if ($cell[$i][$j]['isToday']) {
			$class = 'today';
		}
		else {
			$class = 'withoutLink';
		}

		echo "<td class='$class'>";
		
		// display cell value
		echo $cell[$i][$j]['day'].'<br/>';
		
		// display short desc
		if ($cell[$i][$j]['link'] != 'none') {
			echo "<div class='cellLink'>";
		}
		foreach ($cell[$i][$j]['short_desc'] as $k => $v) {
			if ($cell[$i][$j]['short_desc'][$k]) {
				if ($cell[$i][$j]['short_desc_image'][$k]) {
					echo "{$cell[$i][$j]['short_desc_image'][$k]}";
				}
				echo '<li>'.$cell[$i][$j]['short_desc'][$k].'</li>';
			}
		}
		
		echo '</div></td>';
	}
	
	// end row
	echo '</tr>';
}
?>
</tbody>

<tfoot>
<tr><th colspan='7'><a href="#" onclick="<?= $todayLink; ?>">
Today is <?= $todayText; ?></a></th></tr>
</tfoot>

</table>
